language: php
php: ['7.1']
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - printf "\n" | pecl install imagick
  - composer install
  - php -S localhost:8000 -t web/ &
  - sed -i -e 's/cherryart.local/localhost:8000/g' phpunit.xml.dist
script:
  - bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
